version: '3'

services:
  discovery-server:
    build: ./discovery-server
    image: discovery-server
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    restart: always
    ports:
      - 8761:8761
    networks:
      - new-network

  config-server:
   build: ./config-server
   image: config-server
   ports:
    - 8888:8888
   restart: always
   networks:
    - new-network

  proxy-service:
   build: ./proxy-service
   image: proxy-service
   depends_on: 
    - config-server
    - discovery-server
   restart: always
   ports:
    - 9000:9000
   networks:
    - new-network

  user:
   build: ./user-service
   image: user
   depends_on: 
    - config-server
    - discovery-server
   restart: always
   ports:
    - 9001:9001
   networks:
    - new-network

  zookeeper:
      image: wurstmeister/zookeeper:latest
      ports:
        - "2181:2181"

  kafka:
      image: wurstmeister/kafka:2.12-2.5.0
      ports:
        - "9092:9092"
      environment:
        KAFKA_ADVERTISED_HOST_NAME: 127.0.0.1
        KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
        KAFKA_BROKER_ID: 1
        KAFKA_CREATE_TOPICS: "first_topic:3:1:compact"
      volumes:
        - /var/run/docker.sock:/var/run/docker.sock

networks:
   new-network:
    driver: bridge
