version: '3'

services:
  discovery-server:
    build: ./discovery-server
    image: discovery-server
    environment: 
      - eureka.client.serviceUrl.defaultZone=http://discovery-server:8761/eureka/
    restart: always
    ports:
      - 8761:8761
    networks:
      - new-network

  config-server:
   build: ./config-server
   image: config-server
   ports:
    - 8888:8888
   restart: always
   networks:
    - new-network

  proxy-service:
   build: ./proxy-service
   image: proxy-service
   depends_on: 
    - config-server
    - discovery-server
   restart: always
   ports:
    - 9000:9000
   networks:
    - new-network

  user:
   build: ./user-service
   image: user
   depends_on: 
    - config-server
    - discovery-server
   restart: always
   ports:
    - 9001:9001
   networks:
    - new-network

  log-service:
    build: ./log-service
    image: log-service
    depends_on:
      - config-server
      - discovery-server
    restart: always
    ports:
      - 9002:9002
    networks:
      - new-network

  zookeeper:
   image: wurstmeister/zookeeper
   container_name: zookeeper
   restart: always
   ports:
    - 2181:2181
   networks:
    - new-network

  kafka:
   image: wurstmeister/kafka
   container_name: kafka
   restart: always
   ports:
    - 9092:9092
   depends_on:
    - zookeeper
   links:
    - zookeeper:zookeeper
   environment:
    KAFKA_ADVERTISED_HOST_NAME: kafka
    KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
    KAFKA_CREATE_TOPICS: "logs_topic:3:1:compact"
   networks:
    - new-network

  # Elasticsearch Docker Images: https://www.docker.elastic.co/
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.8.1
    container_name: elasticsearch
    environment:
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK
    ports:
      - 9200:9200
      - 9300:9300
    volumes:
      - elasticsearch-data:/usr/share/elasticsearch/data
    networks:
      - new-network

volumes:
  elasticsearch-data:
    driver: local

networks:
   new-network:
    driver: bridge
